### ISSUE TITLE
Incorrect type for password

### ISSUE THREAD

**Issue by lenart** [RockieStar-Inc/kamal-json-schema#2]
First of - thanks a lot for your effort putting this together. It makes editing `deploy.yml` much more pleasant. 

However when trying it out I had something along this lines defined:
```yaml
registry:
  username: AWS
  password: <%= %x(aws ecr get-login-password) %>
```
and the error `Incorrect type. Expected "array".`. I think we'd need to [change this line](https://github.com/RockieStar-Inc/kamal-json-schema/blob/613627ba64ff8f1c46894b4bbfc65abbbe698ef8/schema.json#L176) from `array` to `string`?

Similarly there's a `string` type requirement for `port` (under `accessories`) where number works just fine. And for `host` we need to use `oneOf` to allow either `host` object or list of IPs defined as an array named `hosts`.
